config/routes.rb
Rails.application.routes.draw do
  resources :users
  mount Avo::Engine, at: Avo.configuration.root_path
  
  resources :orders
  devise_for :clients
  resources :products
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :orders
         has_many :products, through: :orders

   
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :client
  	belongs_to :product

end

app/models/product.rb
class Product < ApplicationRecord
	has_one_attached :image
	has_many :orders
  	has_many :clients, through: :orders
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/avo/clients_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::ClientsController < Avo::ResourcesController
end

app/controllers/avo/orders_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::OrdersController < Avo::ResourcesController
end

app/controllers/avo/products_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::ProductsController < Avo::ResourcesController
end

app/controllers/avo/users_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::UsersController < Avo::ResourcesController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :authenticate_client!
  before_action :correct_client_data ,only:[ :show , :edit , :update ,:destroy ]
  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new

    @order = current_client.orders.build

  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    
    @order = current_client.orders.build(order_params) #Order.new(order_params)
    @order.price =@order.price*@order.quantity
    respond_to do |format|
      if @order.save
        format.html { redirect_to order_url(@order), notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_client_data
      @order=current_client.orders.find_by(id: params[:id])
      redirect_to orders_path ,notice: "Not Authorized"  if @order.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:product_id, :client_id, :quantity, :price ,:email ,:address,:name,:phone)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_path, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :style, :price , :image ,:descreption ,:brand ,:bicycleh_type ,:speed )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">bicycle</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent" >
      <ul class="navbar-nav me-auto mb-2 mb-lg-0  ">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path%>">Home</a>
        </li>

        <%if client_signed_in?%>
          <li class="nav-item">
            <%= link_to "Bicycle",products_path ,class:"nav-link" %>  
          </li>
           <li class="nav-item">
            <%= link_to "My Order",orders_path ,class:"nav-link" %>  
          </li>
          <li class="nav-item"> 
            <%= link_to "Sign Out",  destroy_client_session_path ,data: { turbo_method: :"delete" } ,class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edite Profile",  edit_client_registration_path ,class:"nav-link" %>
          </li>

         
        <%else%>
          <li class="nav-item">
            <%= link_to "Sign In",new_client_session_path ,class:"nav-link" %>     
          </li>
          <li class="nav-item">  
            <%= link_to "Sign Up", new_client_registration_path ,class:"nav-link" %>
          </li>   
        <%end%>
       
      </ul>
      
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<%= stylesheet_link_tag 'home.css', media: 'all', 'data-turbolinks-track' => true%>

<div class="tit">
 <h5>Get your Bike Now!</h5>
 <p>
   <strong>
     Can’t wait another minute to get your hands on the latest bikes?
   </strong>
    <br/>
   Order online and pick up at your local Specialized location or take advantage of FREE shipping on orders
 </p>

<%if client_signed_in? %>
<br/>
<%= link_to "Shop Now" , products_path , class:"btn btn-primary" %>
<%else%>
<br/>
<%= link_to "sign In Now" , new_client_session_path , class:"btn btn-primary" %>
<%end%>
</div>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= notice %></strong> 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bicycle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'home.css', media: 'home', 'data-turbolinks-track' => true%>

  </head>

  <body>
    <%= render 'home/header'%>
    <% if notice %>
    <%= render 'layouts/alert'%>
    <%end%>

    <div class="container" >
        <%= yield %>
    </div>
   
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  
    <%= form.number_field :product_id , value: params[:product_id] ,type: :hidden %>
  </div>

  <div> 
    
    <%= form.number_field :client_id ,value: current_client.id ,type: :hidden %>
  </div>

  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <%= form.text_field :email ,class:"form-control"%>
   
  </div>

   <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Full Name</label>
   <%= form.text_field :name ,class:"form-control"%>
   
  </div>

   <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Phone</label>
    <%= form.text_field :phone ,class:"form-control"%>
  </div>

    <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Full address</label>
   <%= form.text_field :address ,class:"form-control"%>
   
  </div>
  
  <div class="mb-3">
    <%= form.label :quantity, class:"form-label" %>
    <%= form.number_field :quantity ,value: 1 ,class:"form-control"%>
  </div>

  <div class="mb-3">
    <%= form.label :price, class:"form-label" %>
    <%= form.text_field :price ,value: (params[:product_price])   ,:readonly=>true ,class:"form-control" %>
  </div>
  
  <div class="mb-3">
    
    <%= form.submit  class:"btn btn-primary"%>
  </div>
<% end %>

app/views/orders/_order.html.erb
<div id="<%= dom_id order %>">
  <p>
    <strong>Product:</strong>
    <%= order.product_id %>
  </p>

  <p>
    <strong>Client:</strong>
    <%= order.client_id %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= order.quantity %>
  </p>

  <p>
    <strong>cost:</strong>
    <%= order.price %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Orders</h1>

<div id="orders">
<table class="table table-striped table-hover ">
  <thead class="table-dark table-sm">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Address</th>
      <th scope="col">Quantity</th>
      <th scope="col">Product</th>
      <th scope="col">Cost</th>
      <th scope="col">Show</th>
    </tr>
  </thead>
  <tbody>
     <% @orders.each do |order| %>
    
     <% if order.client ==current_client%>
     <tr>
        <th scope="row"><%=order.id%></th>
        <td><%=order.name%></td>
        <td><%=order.email%></td>
        <td><%=order.phone%></td>
        <td><%=order.address%></td>
        <td><%=order.quantity%></td>
         <%  client = Product.find(order.product_id) %>
         
        <td><%=client.name%></td>

        <td><%=order.price %></td>
        <td><%= link_to "Show" , order %></td>
      </tr>
      <%end%>
    
      
      <% end %>
  </tbody>
</table>
  
  
</div>




 
     

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
 
  <%= link_to "Back to orders", orders_path %>

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class:"form-label" %>
    <%= form.text_field :name ,class:"form-control" %>
  </div class="mb-3">

 

    <div class="mb-3">
    <%= form.label :style, class:"form-label" %>
    <%= form.text_field :style, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :price, class:"form-label" %>
    <%= form.text_field :price ,class:"form-control" %>
  </div>

   <div class="mb-3">
    <%= form.label :brand, class:"form-label" %>
    <%= form.text_field :brand ,class:"form-control" %>
  </div>

   <div class="mb-3">
    <%= form.label :speed, class:"form-label" %>
    <%= form.text_field :speed ,class:"form-control" %>
  </div>

   <div class="mb-3">
    <%= form.label :bicycleh_type, class:"form-label" %>
    <%= form.text_field :bicycleh_type ,class:"form-control" %>
  </div>


  <div class="mb-3">
    <%= form.label :descreption, class:"form-label" %>
    <%= form.text_area :descreption ,class:"form-control" %>
  </div>

   <div class="mb-3 field">
    <%= form.label :image, class:"form-label" %>
    <%= form.file_field :image, class:"form-control" %>
  </div>

  <div >
    <%= form.submit class:"btn btn-secondary"%>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
 
  <div class="card" style="width: 18rem;">
 
  <%= image_tag(product.image , height: "200px")%>
  <div class="card-body">
    <h5 class="card-title"><%= product.name %></h5>
    <p class="card-text"> <%= product.style %></p>
    <p class="card-text"><strong>Price:</strong> <%= product.price %></p>
    <%= link_to "Details", product_path(product) ,class:"btn btn-primary"  %>
   
  </div>
</div>

</div>

app/views/products/_productshow.html.erb
<div class="card mb-3">
  <%= image_tag(product.image)%>

 
  <div class="card-body">
    <h3 class="card-title">Name:  <%= product.name %></h3>
    <h4 class="card-title">Price:  $<%= product.price %></h4>
    <p class="card-text">Style:  <%= product.style %></p>
    <p class="card-text">brand:  <%= product.brand %></p>
    <p class="card-text">Speed:  <%= product.speed %></p>
     <p class="card-text">Type:  <%= product.bicycleh_type %></p>
    <p class="card-text"><%= product.descreption %></p>

    <p class="card-text"><small class="text-muted">Last updated <%= product.updated_at  %></small></p>
  </div>
</div>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product ,class:"btn btn-light"%> |
  <%= link_to "Back to products", products_path ,class:"btn btn-light" %>
</div>

app/views/products/index.html.erb
<h1>Products</h1>

<div id="products" class="container d-flex align-content-around flex-wrap" >
  <% @products.each do |product| %>
    <%= render product %>
    
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<%= render 'products/productshow',product: @product %>

<div class="d-flex justify-content-around">

  
  <%= link_to "Back to products", products_path ,class:"btn btn-secondary" %> 
 
  <%= link_to "Buy this bicycle", new_order_path(product_id: @product.id , product_price:@product.price, method: :post) ,class:"btn btn-success" %>


</div>


  <br/>
  <br/>
  <br/>
 

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>